from django.urls import path, include
from .views import (
    BookDetailView,
    ComicDetailView,
    MovieDetailView,
    QuoteDetailView,
    SeriesDetailView,
    ShortStoriesDetailView,
    AllBookView,
    AllComicView,
    AllMovieView,
    AllQuoteView,
    AllSeriesView,
    AllShortStoriesView,
    index,
    quotes,
    books,
    comics,
    movies,
    series,
    short_stories,
    book_details,
    comic_details,
    movie_details,
    series_details,
    short_stories_details,
)

urlpatterns = [
    path('', index, name='index'),
    path('quotes/', quotes, name='quotes'),
    path('books/', books, name='books'),
    path('book_details/<int:pk>/', book_details, name='book_details'),
    path('comics/', comics, name='comics'),
    path('comic_details/<int:pk>/', comic_details, name='comic_details'),
    path('movies/', movies, name='movies'),
    path('movie_details/<int:pk>/', movie_details, name='movie_details'),
    path('series/', series, name='series'),
    path('series_details/<int:pk>/', series_details, name='series_details'),
    path('short_stories/', short_stories, name='short_stories'),
    path('short_stories_details/<int:pk>/', short_stories_details,
            name='short_stories_details'),
    # path('author/<int:pk>/', AuthorDetailView.as_view(), name='author'),
    path('api/quotes/', AllQuoteView.as_view(), name='quotes'),
    path('api/quotes/<int:pk>/', QuoteDetailView.as_view(), name='quote'),
    path('api/books/', AllBookView.as_view(), name='books'),
    path('api/books/<int:pk>/', BookDetailView.as_view(), name='book'),
    path('api/comics/', AllComicView.as_view(), name='comics'),
    path('api/comics/<int:pk>/', ComicDetailView.as_view(), name='comic'),
    # path('director/<int:pk>/', DirectorDetailView.as_view(), name='director'),
    path('api/movies/', AllMovieView.as_view(), name='movies'),
    path('api/movies/<int:pk>/', MovieDetailView.as_view(), name='movie'),
    path('api/series/', AllSeriesView.as_view(), name='series'),
    path('api/series/<int:pk>/', SeriesDetailView.as_view(), name='series'),
    path('api/short_stories/', AllShortStoriesView.as_view(),
         name='short_stories'),
    path('api/short_stories/<int:pk>/', ShortStoriesDetailView.as_view(),
         name='short_stories'),
    # path('illustrator/<int:pk>/', IllustratorDetailView.as_view(),
        #  name='illustrator'),
]
