# Generated by Django 4.2.4 on 2023-09-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.SmallIntegerField(help_text='Unique ID for this quote', primary_key=True, serialize=False)),
                ('quote', models.CharField(help_text='Enter a quote.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShortStories',
            fields=[
                ('id', models.SmallIntegerField(help_text='Unique ID for this short story', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter a short story title.', max_length=200)),
                ('year', models.DateField(max_length=4)),
                ('wiki_url', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the short story', max_length=1000)),
                ('author', models.ManyToManyField(to='app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.SmallIntegerField(help_text='Unique ID for this series', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter a series title.', max_length=200)),
                ('year', models.DateField(max_length=4)),
                ('wiki_url', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the series', max_length=1000)),
                ('director', models.ManyToManyField(to='app.director')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.SmallIntegerField(help_text='Unique ID for this movie', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter a movie title.', max_length=200)),
                ('year', models.DateField(max_length=4)),
                ('wiki_url', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the movie', max_length=1000)),
                ('director', models.ManyToManyField(to='app.director')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.SmallIntegerField(help_text='Unique ID for this comic', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter a comic title.', max_length=200)),
                ('year', models.DateField(max_length=4)),
                ('wiki_url', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the comic', max_length=1000)),
                ('author', models.ManyToManyField(to='app.author')),
                ('illustrator', models.ManyToManyField(to='app.illustrator')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.SmallIntegerField(help_text='Unique ID for this book', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter a book title.', max_length=200)),
                ('year', models.DateField(max_length=4)),
                ('wiki_url', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('author', models.ManyToManyField(to='app.author')),
            ],
        ),
    ]
