# Generated by Django 4.2.4 on 2023-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(help_text='Unique ID for this book', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comic',
            name='id',
            field=models.AutoField(help_text='Unique ID for this comic', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(help_text='Unique ID for this movie', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.AutoField(help_text='Unique ID for this quote', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.AutoField(help_text='Unique ID for this series', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shortstories',
            name='id',
            field=models.AutoField(help_text='Unique ID for this short story', primary_key=True, serialize=False),
        ),
    ]
