# Generated by Django 4.2.4 on 2023-09-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comic_illustrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comic',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the comic', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the movie', max_length=1000),
        ),
        migrations.AlterField(
            model_name='series',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the series', max_length=1000),
        ),
        migrations.AlterField(
            model_name='shortstories',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the short story', max_length=1000),
        ),
    ]
