# Generated by Django 4.2.4 on 2023-09-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_book_summary_alter_comic_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='wiki_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
